# adding param in AWS Systems Manager
AWSTemplateFormatVersion: "2010-09-09"
Description: "This is a param store"
Resources:
  SecretValue:
    Type: AWS::SSM::Parameter # to refer this value in templates {{resolve:ssm", !ImportValue SecretValue, "1}}
    Properties:
      Type: String
      Value: "1"
  
  Environment:
    Type: String
    Default: test
    AllowedValues: [ "test", "prod" ]

Conditions:
  ProdEnv: !Equals [!Ref Environment, "prod"]
  TestEnv: !Equals [!Ref Environment, "test"]

  DatabaseSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: Database credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbuser"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Env
          Value: !Ref Environment
        - Key: Name
          Value: !Join [ "-", [ !Ref Environment, !Ref "AWS::StackName", "secret" ] ] # pseudo param ref
Outputs:
  Svalue:
    Value: !Ref SecretValue
    Export:
      Name: SecretValue
